source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'objectivec-utils_Example' do
  pod "objectivec-utils", :path => "../"
end

target 'objectivec-utils_Tests' do
  pod "objectivec-utils", :path => "../"

  
end
